jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
